import type { Job } from "./domain";

export const candidateSkills = [
  "Product strategy",
  "SQL",
  "Python",
  "Figma",
  "A/B testing",
  "Roadmapping",
  "Analytics",
];

export const jobs: Job[] = [
  {
    id: 1,
    company: "Stripe",
    role: "Senior Product Manager, Growth",
    location: "San Francisco, CA · Hybrid",
    salary: "$174k–$261k",
    source: "LinkedIn",
    posted: "2h ago",
    logo: "S",
    logoColor: "#635bff",
    skills: ["Product strategy", "SQL", "A/B testing"],
    requiredSkills: ["Product strategy", "SQL", "A/B testing"],
    preferredSkills: ["Analytics", "Figma"],
    seniorityMatch: 92,
    preferenceMatch: 96,
    status: "Matched",
    summary: "Lead experimentation and product strategy for Stripe's growth platform.",
  },
  {
    id: 2,
    company: "Notion",
    role: "Product Manager, AI",
    location: "New York, NY · Hybrid",
    salary: "$180k–$245k",
    source: "Indeed",
    posted: "5h ago",
    logo: "N",
    logoColor: "#101010",
    skills: ["Product strategy", "Analytics", "Roadmapping"],
    requiredSkills: ["Product strategy", "Analytics", "Roadmapping"],
    preferredSkills: ["Python", "Figma"],
    seniorityMatch: 88,
    preferenceMatch: 90,
    status: "Prepared",
    summary: "Shape AI experiences that make knowledge work faster and more intuitive.",
  },
  {
    id: 3,
    company: "Airbnb",
    role: "Technical Product Manager",
    location: "Remote · US",
    salary: "$160k–$220k",
    source: "Jobright",
    posted: "Yesterday",
    logo: "A",
    logoColor: "#ff385c",
    skills: ["SQL", "Python", "Analytics"],
    requiredSkills: ["SQL", "Python", "Analytics"],
    preferredSkills: ["A/B testing", "Product strategy"],
    seniorityMatch: 80,
    preferenceMatch: 100,
    status: "Submitted",
    summary: "Own platform capabilities used across Airbnb's global marketplace.",
  },
  {
    id: 4,
    company: "Linear",
    role: "Product Lead",
    location: "Remote",
    salary: "$170k–$230k",
    source: "Company site",
    posted: "2d ago",
    logo: "L",
    logoColor: "#5e6ad2",
    skills: ["Product strategy", "Figma", "Roadmapping"],
    requiredSkills: ["Product strategy", "Figma", "Roadmapping"],
    preferredSkills: ["Analytics"],
    seniorityMatch: 90,
    preferenceMatch: 100,
    status: "Interviewing",
    summary: "Define focused, high-craft workflows for modern product teams.",
  },
];

export const activity = [
  { icon: "mail", title: "Interview invitation", detail: "Linear · Product Lead", time: "18 min ago" },
  { icon: "file", title: "Resume package ready", detail: "Notion · Product Manager, AI", time: "1h ago" },
  { icon: "check", title: "Application confirmed", detail: "Airbnb · Technical Product Manager", time: "Yesterday" },
];
